"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, Download, Ellipsis, FilePlus2, Filter } from "lucide-react";
import { invoices as seedInvoices } from "@/lib/demo-data";
import type { Invoice, Status } from "@/lib/types";
import { AddButton, Badge, Button, Field, Modal, PageHeader, SearchField } from "./ui";

const tone = (status: Status) => status === "Paid" ? "success" : status === "Late" || status === "Not Sent" ? "danger" : "info";

export function InvoicesView({ initialStatus = "All", initialPaid }: { initialStatus?: string; initialPaid?: boolean }) {
  const [invoices, setInvoices] = useState(seedInvoices);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState(initialStatus);
  const [open, setOpen] = useState(false);
  const [monthOpen, setMonthOpen] = useState(false);
  const [month, setMonth] = useState("2026-06");
  const monthLabel = month ? new Date(`${month}-01T12:00:00`).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : "";
  const filtered = useMemo(() => invoices.filter((invoice) => (status === "All" || invoice.status === status) && (initialPaid === undefined || invoice.paid === initialPaid) && (!monthLabel || invoice.month === monthLabel) && `${invoice.client} ${invoice.id}`.toLowerCase().includes(query.toLowerCase())), [initialPaid, invoices, monthLabel, query, status]);
  function togglePaid(invoice: Invoice) { setInvoices((list) => list.map((item) => item.id === invoice.id ? { ...item, paid: !item.paid, status: !item.paid ? "Paid" : "Sent" } : item)); }

  function exportLedger() {
    const csv = [["Invoice", "Client", "Month", "Amount", "Due", "Sent", "Status"], ...filtered.map((invoice) => [invoice.id, invoice.client, invoice.month, String(invoice.amount), invoice.due, invoice.sent || "", invoice.status])]
      .map((row) => row.map((value) => `"${value.replaceAll("\"", "\"\"")}"`).join(",")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = `invoice-ledger-${month || "all"}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }
  return <>
    <PageHeader eyebrow="Permanent financial ledger" title="Invoices" description="Monthly snapshots stay immutable when client services change." action={<AddButton onClick={() => setOpen(true)} testId="create-invoice">Create invoice</AddButton>} secondary={<Button variant="secondary" onClick={exportLedger}><Download size={15} />Export ledger</Button>} />
    <section className="mini-stats"><div className="mini-stat"><span>Invoiced this month</span><strong>$31.2K</strong></div><div className="mini-stat"><span>Paid</span><strong style={{ color: "var(--green)" }}>$16.4K</strong></div><div className="mini-stat"><span>Receivables</span><strong>$14.7K</strong></div><div className="mini-stat"><span>Sent 5+ days early</span><strong>72%</strong></div></section>
    <section className="panel" data-testid="invoice-ledger"><div className="toolbar"><div className="toolbar-group"><SearchField value={query} onChange={setQuery} placeholder="Search invoice or client…" /><Button variant="secondary" onClick={() => setMonthOpen(true)}><Filter size={15} />{monthLabel || "All months"}</Button></div><div className="filter-tabs">{["All", "Paid", "Sent", "Late", "Not Sent"].map((value) => <button className={status === value ? "active" : ""} key={value} onClick={() => setStatus(value)}>{value}</button>)}</div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Client</th><th>Billing month</th><th>Amount</th><th>Due</th><th>Sent</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((invoice) => <tr key={invoice.id}><td><Link className="record-link" href={`/invoices/${invoice.id}`}>{invoice.id}</Link></td><td><Link className="row-link" href={`/invoices/${invoice.id}`}><strong>{invoice.client}</strong></Link></td><td>{invoice.month}</td><td><strong>${invoice.amount.toLocaleString()}</strong></td><td>{invoice.due}</td><td>{invoice.sent || "—"}</td><td><button style={{ border: 0, background: "transparent", padding: 0 }} onClick={() => togglePaid(invoice)} title="Toggle paid"><Badge tone={tone(invoice.status)}>{invoice.status}</Badge></button></td><td><Link className="table-action table-action-link" href={`/invoices/${invoice.id}`} aria-label={`Open ${invoice.id}`}><Ellipsis size={16} /></Link></td></tr>)}</tbody></table></div></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Create invoice snapshot" description="Normally generated by the idempotent monthly billing job." footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => setOpen(false)}><Check size={16} />Create invoice</Button></>}><div className="form-grid"><Field label="Client"><select><option>Northstar Dental</option><option>Atlas Legal Group</option></select></Field><Field label="Billing month"><input type="month" defaultValue="2026-06" /></Field><Field label="Issue date"><input type="date" defaultValue="2026-06-20" /></Field><Field label="Amount" hint="Captured from active service MRR"><input value="$4,850" readOnly /></Field><div className="field full"><div className="demo-note"><FilePlus2 size={15} /> One unique invoice per client and billing month. Historical amounts cannot be rebuilt.</div></div></div></Modal>
    <Modal open={monthOpen} onClose={() => setMonthOpen(false)} title="Filter invoice month" footer={<><Button variant="secondary" onClick={() => { setMonth(""); setMonthOpen(false); }}>All months</Button><Button onClick={() => setMonthOpen(false)}>Apply month</Button></>}><Field label="Billing month"><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></Field></Modal>
  </>;
}
