import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import mongoose from 'mongoose';
import morgan from 'morgan';
import { env } from './config/env.js';
import { requireAuth } from './middleware/auth.js';
import { errorHandler, notFound } from './middleware/error.js';
import { authRouter } from './routes/auth.js';
import { usersRouter } from './routes/users.js';
import { clientsRouter } from './routes/clients.js';
import { clientServicesRouter, servicesRouter } from './routes/services.js';
import { invoicesRouter } from './routes/invoices.js';
import { onboardingRouter } from './routes/onboarding.js';
import { complaintsRouter, contactsRouter, reportsRouter, upsellsRouter } from './routes/operations.js';
import { dashboardRouter } from './routes/dashboard.js';
import { systemRouter } from './routes/system.js';
import { activitiesRouter } from './routes/activities.js';
import { salesIntegrationRouter } from './routes/sales-integration.js';

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((x) => x.trim()), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.get('/api/health', (_req, res) => res.json({ success: true, data: { status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected', timestamp: new Date().toISOString() } }));
app.use('/api/auth', authRouter);
app.use('/api/integrations/sales', salesIntegrationRouter);
app.use('/api/users', requireAuth, usersRouter);
app.use('/api/clients', requireAuth, clientsRouter);
app.use('/api/clients/:clientId/services', requireAuth, clientServicesRouter);
app.use('/api/services', requireAuth, servicesRouter);
app.use('/api/invoices', requireAuth, invoicesRouter);
app.use('/api/onboarding', requireAuth, onboardingRouter);
app.use('/api/contacts', requireAuth, contactsRouter);
app.use('/api/complaints', requireAuth, complaintsRouter);
app.use('/api/reports', requireAuth, reportsRouter);
app.use('/api/upsells', requireAuth, upsellsRouter);
app.use('/api/dashboard', requireAuth, dashboardRouter);
app.use('/api/activities', requireAuth, activitiesRouter);
app.use('/api/system', systemRouter);
app.use(notFound);
app.use(errorHandler);
